export const compatibilityParams = [
    {
        name: 'strictest search',
        relaxRoboticness: false,
        alternateBPM: false,
        removeKeyCheck: false,
        broadenLevels: false,
        removeRoboticnessCheck: false,
        excludeHoursOff: false,
        removeBPMCheck: false,
        removeDelayChecks: false,
        removeGenreLock: false,
        removeYearLock: false,
    },
    {
        name: 'relax roboticness',
        relaxRoboticness: true,
        alternateBPM: false,
        removeKeyCheck: false,
        broadenLevels: false,
        removeRoboticnessCheck: false,
        excludeHoursOff: false,
        removeBPMCheck: false,
        removeDelayChecks: false,
        removeGenreLock: false,
        removeYearLock: false,
    },
    {
        name: 'alternate bpm',
        relaxRoboticness: true,
        alternateBPM: true,
        removeKeyCheck: false,
        broadenLevels: false,
        removeRoboticnessCheck: false,
        excludeHoursOff: false,
        removeBPMCheck: false,
        removeDelayChecks: false,
        removeGenreLock: false,
        removeYearLock: false,
    },
    {
        name: 'remove key check',
        relaxRoboticness: true,
        alternateBPM: false,
        removeKeyCheck: true,
        broadenLevels: false,
        removeRoboticnessCheck: false,
        excludeHoursOff: false,
        removeBPMCheck: false,
        removeDelayChecks: false,
        removeGenreLock: false,
        removeYearLock: false,
    },
    {
        name: 'remove bpm check',
        relaxRoboticness: true,
        alternateBPM: false,
        removeKeyCheck: false,
        broadenLevels: false,
        removeRoboticnessCheck: false,
        excludeHoursOff: false,
        removeBPMCheck: true,
        removeDelayChecks: false,
        removeGenreLock: false,
        removeYearLock: false,
    },
    {
        name: 'remove roboticness check',
        relaxRoboticness: true,
        alternateBPM: false,
        removeKeyCheck: false,
        broadenLevels: false,
        removeRoboticnessCheck: true,
        excludeHoursOff: false,
        removeBPMCheck: false,
        removeDelayChecks: false,
        removeGenreLock: false,
        removeYearLock: false,
    },
    {
        name: 'remove delay checks',
        relaxRoboticness: true,
        alternateBPM: false,
        removeKeyCheck: false,
        broadenLevels: false,
        removeRoboticnessCheck: false,
        excludeHoursOff: false,
        removeBPMCheck: false,
        removeDelayChecks: true,
        removeGenreLock: false,
        removeYearLock: false,
    },
    {
        name: 'broaden levels',
        relaxRoboticness: true,
        alternateBPM: false,
        removeKeyCheck: false,
        broadenLevels: true,
        removeRoboticnessCheck: false,
        excludeHoursOff: false,
        removeBPMCheck: false,
        removeDelayChecks: false,
        removeGenreLock: false,
        removeYearLock: false,
    },
    {
        name: 'no hours off check',
        relaxRoboticness: true,
        alternateBPM: false,
        removeKeyCheck: false,
        broadenLevels: false,
        removeRoboticnessCheck: false,
        excludeHoursOff: true,
        removeBPMCheck: false,
        removeDelayChecks: false,
        removeGenreLock: false,
        removeYearLock: false,
    },
    {
        name: 'no hours off check / alternate bpm',
        relaxRoboticness: true,
        alternateBPM: true,
        removeKeyCheck: false,
        broadenLevels: false,
        removeRoboticnessCheck: false,
        excludeHoursOff: true,
        removeBPMCheck: false,
        removeDelayChecks: false,
        removeGenreLock: false,
        removeYearLock: false,
    },
    {
        name: 'broadest search - by play count only',
        relaxRoboticness: true,
        alternateBPM: false,
        removeKeyCheck: true,
        broadenLevels: false,
        removeRoboticnessCheck: true,
        excludeHoursOff: true,
        removeBPMCheck: true,
        removeDelayChecks: true,
        removeGenreLock: true,
        removeYearLock: true,
    },
]
